# Generated by Django 4.2.2 on 2023-06-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_student_registration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='students_count',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='tutors_count',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
