# Generated by Django 4.2.2 on 2023-06-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_grades_students_count_grades_tutors_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='timeslots',
            field=models.ManyToManyField(to='mainapp.timeslot'),
        ),
    ]
