# Generated by Django 4.2.2 on 2023-06-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_timeslot_tutor_registration_timeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor_registration',
            name='price_group_hr',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='price_group_session',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='price_oneonone_hr',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tutor_registration',
            name='price_oneonone_session',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
